### ISSUE TITLE
Error when running EmailChecker.valid?

### ISSUE THREAD

**Issue by lowks** [jshmrtn/email_checker#7] opened 2017-07-06 04:08 UTC
I get this error when using `EmailChecker.valid?`: 

```
     ** (FunctionClauseError) no function clause matching in Kernel.=~/2
     stacktrace:
       (elixir) lib/kernel.ex:1580: Kernel.=~(nil, ~r/^(?<user>[^\s]+)@(?<domain>[^\s]+\.[^\s]+)$/)
       lib/email_checker.ex:28: EmailChecker.valid?/2```

**Comment by rhnonose** [comment] 2017-09-28 15:30
I'm facing a similar error.

**Comment by maennchen** [comment] 2017-09-29 11:53
The issue is that `nil` was passed as an argument for `email`. The parameter should be checked in `valid?/2` instead of `Kernel.=~/2`.

**Comment by maennchen** [comment] 2017-09-29 11:54
Fixed with 3045e12944b19cf362ee4c06ba3fa58eaac95dcc

**Closed by maennchen** 2017-09-29 11:54 UTC
Labels: bug
